=== script-solution/Boardsolution/bbceditor/extra_tags.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.script-solution.de/schemas/bs/bbc/extra_tags"
	xmlns:tns="http://www.script-solution.de/schemas/bs/bbc/extra_tags"
	elementFormDefault="qualified">
	<!-- Type definitions -->
	<complexType name="extraTagsType">
		<sequence>
			<element name="buttons" type="tns:buttonsType"/>
			<element name="items" type="tns:itemsType"/>
		</sequence>
	</complexType>
	
	<complexType name="buttonsType">
		<sequence>
			<element name="button" type="tns:buttonType" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	
	<complexType name="buttonType">
		<sequence>
			<element name="tooltip" type="string" minOccurs="0"/>
			<element name="image" type="string" minOccurs="0"/>
		</sequence>
		<attribute name="name" type="string" use="required"/>
	</complexType>
	
	<complexType name="itemsType">
		<sequence>
			<element name="item" type="tns:itemType" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	
	<complexType name="itemType">
		<sequence>
			<element name="buttonID" type="string" minOccurs="0"/>
			<element name="comboName" type="string" minOccurs="0"/>
			<element name="dialogTitle" type="string" minOccurs="0"/>
			<element name="parameterTitle" type="string" minOccurs="0"/>
			<element name="hasParameter" type="boolean" minOccurs="0"/>
			<element name="description" type="string" minOccurs="0"/>
		</sequence>
		<attribute name="name" type="string" use="required"/>
	</complexType>

	<!-- Content -->
	<element name="extraTags" type="tns:extraTagsType"/>
</schema>

=== script-solution/Boardsolution/bbceditor/extra_tags.xml
<?xml version="1.0" encoding="UTF-8"?>
<extraTags xmlns="http://www.script-solution.de/schemas/bs/bbc/extra_tags"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.script-solution.de/schemas/bs/bbc/extra_tags extra_tags.xsd">
	<buttons>
		<button name="b1">
			<tooltip>gui.dialog.extra.links.tooltip</tooltip>
			<image>./images/paste_extra.png</image>
		</button>
	</buttons>
	<items>
		<item name="post">
			<buttonID>b1</buttonID>
			<comboName>gui.dialog.extra.post.comboname</comboName>
			<dialogTitle>gui.dialog.extra.post.title</dialogTitle>
			<parameterTitle>gui.dialog.extra.post.parameter.title</parameterTitle>
			<hasParameter>true</hasParameter>
			<description>gui.dialog.extra.post.desc</description>
		</item>
		<item name="topic">
			<buttonID>b1</buttonID>
			<comboName>gui.dialog.extra.topic.comboname</comboName>
			<dialogTitle>gui.dialog.extra.topic.title</dialogTitle>
			<parameterTitle>gui.dialog.extra.topic.parameter.title</parameterTitle>
			<hasParameter>true</hasParameter>
			<description>gui.dialog.extra.topic.desc</description>
		</item>
		<item name="att">
			<buttonID>b1</buttonID>
			<comboName>gui.dialog.extra.att.comboname</comboName>
			<dialogTitle>gui.dialog.extra.att.title</dialogTitle>
			<parameterTitle>gui.dialog.extra.att.parameter.title</parameterTitle>
			<hasParameter>true</hasParameter>
			<description>gui.dialog.extra.att.desc</description>
		</item>
		<item name="attimg">
			<buttonID>b1</buttonID>
			<comboName>gui.dialog.extra.attimg.comboname</comboName>
			<dialogTitle>gui.dialog.extra.attimg.title</dialogTitle>
			<parameterTitle>gui.dialog.extra.attimg.parameter.title</parameterTitle>
			<hasParameter>false</hasParameter>
			<description>gui.dialog.extra.attimg.desc</description>
		</item>
	</items>
</extraTags>
