=== script-solution/Boardsolution/bbceditor/highlighter/language.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.script-solution.de/schemas/bs/bbc/language"
	xmlns:tns="http://www.script-solution.de/schemas/bs/bbc/language"
	elementFormDefault="qualified">
	<!-- Type definitions -->
	<complexType name="highlighterType">
		<sequence>
			<!-- The name of the language / format -->
			<element name="name" type="string"/>
			<!-- Wether numbers should be highlighted -->
			<element name="hlNumbers" type="boolean"/>
			<!-- What character is used to escape other ones? -->
			<element name="escapeChar" type="string"/>
			<!-- Quotes that encapsulate strings -->
			<element name="stringQuotes" type="tns:defsType"/>
			<!-- Single-line comments -->
			<element name="slComments" type="tns:defsType"/>
			<!-- Multi-line comments -->
			<element name="mlComments" type="tns:mlDefsType"/>
			<!-- Symbols -->
			<element name="symbols" type="tns:kwsType"/>
			<!-- Regular expressions -->
			<element name="regexps" type="tns:regexpsType"/>
			<!-- Keywords -->
			<element name="keywords" type="tns:keywordsType"/>
			<!-- Colors. To define the style for the elements above -->
			<element name="colors" type="tns:colorsType"/>
		</sequence>
	</complexType>
	
	<!-- a list of def-elements -->
	<complexType name="defsType">
		<sequence>
			<element name="def" type="tns:defType" minOccurs="0" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	
	<!-- the base def-element -->
	<complexType name="defType">
		<simpleContent>
			<extension base="string">
				<attribute name="id" type="string" use="required"/>
			</extension>
		</simpleContent>
	</complexType>
	
	<!-- a list of def-elements for the multiline-comments -->
	<complexType name="mlDefsType">
		<sequence>
			<element name="def" type="tns:mlDefType" minOccurs="0" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	
	<!-- the def-element for multiline-comments -->
	<complexType name="mlDefType">
		<simpleContent>
			<extension base="tns:defType">
				<attribute name="start" type="string" use="required"/>
				<attribute name="end" type="string" use="required"/>
			</extension>
		</simpleContent>
	</complexType>

	<!-- a list of kw-elements -->
	<complexType name="kwsType">
		<sequence>
			<element name="kw" type="string" minOccurs="0" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	
	<!-- the regex element -->
	<complexType name="regexpsType">
		<sequence>
			<element name="def" type="tns:regexpDefType" minOccurs="0" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	
	<!-- the def-element for the regexps -->
	<complexType name="regexpDefType">
		<simpleContent>
			<extension base="tns:defType">
				<attribute name="pattern" type="string" use="required"/>
				<attribute name="cs" type="boolean"/>
				<attribute name="group" type="integer"/>
			</extension>
		</simpleContent>
	</complexType>
	
	<!-- the keywords-element -->
	<complexType name="keywordsType">
		<sequence>
			<element name="def" type="tns:keywordDefType" minOccurs="0" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	
	<!-- the def-element for the keywords -->
	<complexType name="keywordDefType">
		<sequence>
			<element name="kw" type="string" minOccurs="0" maxOccurs="unbounded"/>
		</sequence>
		<attribute name="id" type="string" use="required"/>
		<attribute name="cs" type="boolean"/>
		<attribute name="reqWord" type="boolean"/>
	</complexType>
	
	<!-- the color-element -->
	<complexType name="colorsType">
		<sequence>
			<element name="numbers" type="tns:simpleStylesType" minOccurs="0"/>
			<element name="strings" type="tns:idStylesType" minOccurs="0" maxOccurs="unbounded"/>
			<element name="slComments" type="tns:idStylesType" minOccurs="0" maxOccurs="unbounded"/>
			<element name="mlComments" type="tns:idStylesType" minOccurs="0" maxOccurs="unbounded"/>
			<element name="symbols" type="tns:simpleStylesType" minOccurs="0"/>
			<element name="regexp" type="tns:idStylesType" minOccurs="0" maxOccurs="unbounded"/>
			<element name="keywords" type="tns:idStylesType" minOccurs="0" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	
	<!-- a list of attr-elements for an element with no id -->
	<complexType name="simpleStylesType">
		<sequence>
			<element name="attr" type="tns:styleType" minOccurs="0" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	
	<!-- a list of attr-elements for an element with id -->
	<complexType name="idStylesType">
		<sequence>
			<element name="attr" type="tns:styleType" minOccurs="0" maxOccurs="unbounded"/>
		</sequence>
		<attribute name="id" type="string" use="required"/>
	</complexType>
	
	<!-- the attr-element -->
	<complexType name="styleType">
		<attribute name="name" type="tns:styleNameType" use="required"/>
		<attribute name="value" type="string" use="required"/>
	</complexType>
	
	<!-- The styles that can be used -->
	<simpleType name="styleNameType">
		<restriction base="string">
			<!-- toggle-attributes (true/false) -->
			<enumeration value="bold"/>
			<enumeration value="italic"/>
			<enumeration value="underline"/>
			<enumeration value="strike"/>
			<!-- The position (sup,sub) -->
			<enumeration value="pos"/>
			<!-- A link/email with an URL. You may use {text} in the value which will be the matched text -->
			<enumeration value="URL"/>
			<enumeration value="email"/>
			<!-- Colors (#[a-fA-F]{6}) -->
			<enumeration value="bgColor"/>
			<enumeration value="fontColor"/>
			<!-- Font family -->
			<enumeration value="fontFamily"/>
			<!-- Font size (pixel) -->
			<enumeration value="fontSize"/>
		</restriction>
	</simpleType>
	
	<!-- Content -->
	<element name="highlighter" type="tns:highlighterType"/>
</schema>

=== script-solution/Boardsolution/bbceditor/highlighter/c.xml
<?xml version="1.0" encoding="UTF-8"?>
<highlighter xmlns="http://www.script-solution.de/schemas/bs/bbc/language"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.script-solution.de/schemas/bs/bbc/language language.xsd">
	<name>C</name>
	<hlNumbers>true</hlNumbers>
	<escapeChar>\</escapeChar>
	<stringQuotes>
		<def id="2">&quot;</def>
		<def id="1">&#039;</def>
	</stringQuotes>
	<slComments>
		<def id="2">#</def>
		<def id="1">//</def>
	</slComments>
	<mlComments>
		<def id="1" start="/*" end="*/"/>
	</mlComments>
	<symbols>
		<kw>!</kw>
		<kw>&amp;</kw>
		<kw>%</kw>
		<kw>*</kw>
		<kw>+</kw>
		<kw>(</kw>
		<kw>)</kw>
		<kw>.</kw>
		<kw>/</kw>
		<kw>-</kw>
		<kw>;</kw>
		<kw>]</kw>
		<kw>:</kw>
		<kw>}</kw>
		<kw>::</kw>
		<kw>^</kw>
		<kw>{</kw>
		<kw>&gt;</kw>
		<kw>=</kw>
		<kw>[</kw>
		<kw>&lt;</kw>
	</symbols>
	<regexps>
	</regexps>
	<keywords>
		<def id="2" cs="false">
			<kw>volatile</kw>
			<kw>static</kw>
			<kw>const</kw>
			<kw>char</kw>
			<kw>signed</kw>
			<kw>int</kw>
			<kw>true</kw>
			<kw>void</kw>
			<kw>double</kw>
			<kw>long</kw>
			<kw>unsigned</kw>
			<kw>typedef</kw>
			<kw>float</kw>
			<kw>register</kw>
			<kw>short</kw>
			<kw>wchar_t</kw>
			<kw>struct</kw>
			<kw>sizeof</kw>
			<kw>string</kw>
			<kw>union</kw>
			<kw>false</kw>
			<kw>auto</kw>
			<kw>null</kw>
		</def>
		<def id="1" cs="false">
			<kw>else</kw>
			<kw>for</kw>
			<kw>return</kw>
			<kw>goto</kw>
			<kw>enum</kw>
			<kw>switch</kw>
			<kw>function</kw>
			<kw>while</kw>
			<kw>break</kw>
			<kw>default</kw>
			<kw>if</kw>
			<kw>extern</kw>
			<kw>inline</kw>
			<kw>continue</kw>
			<kw>do</kw>
			<kw>case</kw>
		</def>
	</keywords>
	<colors>
		<numbers>
			<attr name="fontColor" value="#800080"/>
		</numbers>
		<strings id="2">
			<attr name="fontColor" value="#FF00FF"/>
		</strings>
		<strings id="1">
			<attr name="fontColor" value="#FF00FF"/>
		</strings>
		<slComments id="2">
			<attr name="fontColor" value="#008080"/>
		</slComments>
		<slComments id="1">
			<attr name="fontColor" value="#008000"/>
		</slComments>
		<mlComments id="1">
			<attr name="fontColor" value="#0000FF"/>
		</mlComments>
		<symbols>
			<attr name="fontColor" value="#800000"/>
		</symbols>
		<keywords id="2">
			<attr name="fontColor" value="#2E8B57"/>
			<attr name="bold" value="true"/>
		</keywords>
		<keywords id="1">
			<attr name="fontColor" value="#A52A2A"/>
			<attr name="bold" value="true"/>
		</keywords>
	</colors>
</highlighter>

=== script-solution/Boardsolution/bbceditor/highlighter/xml.xml
<?xml version="1.0" encoding="UTF-8"?>
<highlighter xmlns="http://www.script-solution.de/schemas/bs/bbc/language"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.script-solution.de/schemas/bs/bbc/language language.xsd">
	<name>XML</name>
	<hlNumbers>false</hlNumbers>
	<escapeChar>\</escapeChar>
	<stringQuotes>
		<def id="2">&#039;</def>
		<def id="1">&quot;</def>
	</stringQuotes>
	<slComments>
	</slComments>
	<mlComments>
		<def id="1" start="&lt;!--" end="--&gt;"/>
	</mlComments>
	<symbols>
	</symbols>
	<regexps>
		<def id="1" pattern="([a-z_\-:]+)(=)" cs="0" group="1"/>
		<def id="2" pattern="(&lt;[\/?|(\?xml)]?[a-z0-9_\-:]*(\??&gt;)?)" cs="0" group="1"/>
		<def id="3" pattern="(([\/|\?])?&gt;)" cs="0" group="1"/>
		<def id="4" pattern="&amp;.+?;"/>
	</regexps>
	<keywords>
	</keywords>
	<colors>
		<numbers>
		</numbers>
		<strings id="2">
			<attr name="fontColor" value="#FF00FF"/>
		</strings>
		<strings id="1">
			<attr name="fontColor" value="#FF00FF"/>
		</strings>
		<mlComments id="1">
			<attr name="fontColor" value="#0000FF"/>
		</mlComments>
		<regexp id="1">
			<attr name="fontColor" value="#6a5ada"/>
		</regexp>
		<regexp id="2">
			<attr name="fontColor" value="#008a8c"/>
		</regexp>
		<regexp id="3">
			<attr name="fontColor" value="#008a8c"/>
		</regexp>
		<regexp id="4">
			<attr name="fontColor" value="#a04bf8"/>
		</regexp>
	</colors>
</highlighter>

=== script-solution/Boardsolution/bbceditor/highlighter/cpp.xml
<?xml version="1.0" encoding="UTF-8"?>
<highlighter xmlns="http://www.script-solution.de/schemas/bs/bbc/language"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.script-solution.de/schemas/bs/bbc/language language.xsd">
	<name>C++</name>
	<hlNumbers>true</hlNumbers>
	<escapeChar>\</escapeChar>
	<stringQuotes>
		<def id="2">&quot;</def>
		<def id="1">&#039;</def>
	</stringQuotes>
	<slComments>
		<def id="2">#</def>
		<def id="1">//</def>
	</slComments>
	<mlComments>
		<def id="1" start="/*" end="*/"/>
	</mlComments>
	<symbols>
		<kw>!</kw>
		<kw>&amp;</kw>
		<kw>%</kw>
		<kw>*</kw>
		<kw>+</kw>
		<kw>(</kw>
		<kw>)</kw>
		<kw>.</kw>
		<kw>/</kw>
		<kw>-</kw>
		<kw>;</kw>
		<kw>]</kw>
		<kw>:</kw>
		<kw>}</kw>
		<kw>::</kw>
		<kw>^</kw>
		<kw>{</kw>
		<kw>&gt;</kw>
		<kw>=</kw>
		<kw>[</kw>
		<kw>&lt;</kw>
	</symbols>
	<regexps>
	</regexps>
	<keywords>
		<def id="3" cs="false">
			<kw>pow</kw>
			<kw>memmove</kw>
			<kw>asctime</kw>
			<kw>freopen</kw>
			<kw>sprintf</kw>
			<kw>memchr</kw>
			<kw>strncat</kw>
			<kw>ispunct</kw>
			<kw>malloc</kw>
			<kw>scanf</kw>
			<kw>strxfrm</kw>
			<kw>free</kw>
			<kw>time</kw>
			<kw>abs</kw>
			<kw>memcpy</kw>
			<kw>perror</kw>
			<kw>rand</kw>
			<kw>strspn</kw>
			<kw>isprint</kw>
			<kw>memset</kw>
			<kw>fscanf</kw>
			<kw>fgetc</kw>
			<kw>frexp</kw>
			<kw>sscanf</kw>
			<kw>strtoul</kw>
			<kw>ctime</kw>
			<kw>log</kw>
			<kw>snprintf</kw>
			<kw>exit</kw>
			<kw>tolower</kw>
			<kw>system</kw>
			<kw>vsprintf</kw>
			<kw>floor</kw>
			<kw>ferror</kw>
			<kw>fseek</kw>
			<kw>fflush</kw>
			<kw>tan</kw>
			<kw>offsetof</kw>
			<kw>remove</kw>
			<kw>ceil</kw>
			<kw>ldiv</kw>
			<kw>modf</kw>
			<kw>rewind</kw>
			<kw>ftell</kw>
			<kw>fabs</kw>
			<kw>strcspn</kw>
			<kw>strtok</kw>
			<kw>fgets</kw>
			<kw>strtod</kw>
			<kw>ungetc</kw>
			<kw>isalpha</kw>
			<kw>qsort</kw>
			<kw>fputc</kw>
			<kw>isupper</kw>
			<kw>isgraph</kw>
			<kw>strftime</kw>
			<kw>strncpy</kw>
			<kw>localtime</kw>
			<kw>ldexp</kw>
			<kw>strerror</kw>
			<kw>strchr</kw>
			<kw>clock</kw>
			<kw>sqrt</kw>
			<kw>realloc</kw>
			<kw>fputs</kw>
			<kw>toupper</kw>
			<kw>strrchr</kw>
			<kw>atexit</kw>
			<kw>strcpy</kw>
			<kw>clearerr</kw>
			<kw>va_arg</kw>
			<kw>sin</kw>
			<kw>assert</kw>
			<kw>abort</kw>
			<kw>atol</kw>
			<kw>strncmp</kw>
			<kw>atan</kw>
			<kw>cos</kw>
			<kw>rename</kw>
			<kw>setvbuf</kw>
			<kw>isdigit</kw>
			<kw>putchar</kw>
			<kw>tanh</kw>
			<kw>strlen</kw>
			<kw>isxdigit</kw>
			<kw>calloc</kw>
			<kw>puts</kw>
			<kw>strpbrk</kw>
			<kw>vfprintf</kw>
			<kw>isspace</kw>
			<kw>atof</kw>
			<kw>atoi</kw>
			<kw>setjmp</kw>
			<kw>tmpname</kw>
			<kw>feof</kw>
			<kw>cosh</kw>
			<kw>strtol</kw>
			<kw>strstr</kw>
			<kw>fopen</kw>
			<kw>sinh</kw>
			<kw>fwrite</kw>
			<kw>gmtime</kw>
			<kw>fmod</kw>
			<kw>difftime</kw>
			<kw>strcat</kw>
			<kw>getchar</kw>
			<kw>exp</kw>
			<kw>fsetpos</kw>
			<kw>labs</kw>
			<kw>srand</kw>
			<kw>sizeof</kw>
			<kw>iscntrl</kw>
			<kw>setbuf</kw>
			<kw>fprintf</kw>
			<kw>fclose</kw>
			<kw>asin</kw>
			<kw>div</kw>
			<kw>tmpfile</kw>
			<kw>bsearch</kw>
			<kw>atan2</kw>
			<kw>longjmp</kw>
			<kw>strcmp</kw>
			<kw>fgetpos</kw>
			<kw>mktime</kw>
			<kw>vprintf</kw>
			<kw>acos</kw>
			<kw>isalnum</kw>
			<kw>printf</kw>
			<kw>getenv</kw>
			<kw>putc</kw>
			<kw>va_start</kw>
			<kw>fread</kw>
			<kw>gets</kw>
			<kw>va_end</kw>
			<kw>log10</kw>
			<kw>islower</kw>
			<kw>getc</kw>
			<kw>strcoll</kw>
			<kw>memcmp</kw>
		</def>
		<def id="2" cs="false">
			<kw>tm</kw>
			<kw>raise</kw>
			<kw>const</kw>
			<kw>char</kw>
			<kw>size_t</kw>
			<kw>signal</kw>
			<kw>long</kw>
			<kw>float</kw>
			<kw>longint</kw>
			<kw>short</kw>
			<kw>div_t</kw>
			<kw>struct</kw>
			<kw>extern</kw>
			<kw>union</kw>
			<kw>FILE</kw>
			<kw>false</kw>
			<kw>ldiv_t</kw>
			<kw>null</kw>
			<kw>volatile</kw>
			<kw>static</kw>
			<kw>clock_t</kw>
			<kw>signed</kw>
			<kw>int</kw>
			<kw>ptrdiff_t</kw>
			<kw>void</kw>
			<kw>true</kw>
			<kw>double</kw>
			<kw>unsigned</kw>
			<kw>typedef</kw>
			<kw>register</kw>
			<kw>fpos_t</kw>
			<kw>va_list</kw>
			<kw>jmp_buf</kw>
			<kw>time_t</kw>
			<kw>shortint</kw>
			<kw>auto</kw>
			<kw>bool</kw>
		</def>
		<def id="1" cs="false">
			<kw>virtual</kw>
			<kw>using</kw>
			<kw>for</kw>
			<kw>catch</kw>
			<kw>switch</kw>
			<kw>goto</kw>
			<kw>const_cast</kw>
			<kw>private</kw>
			<kw>function</kw>
			<kw>namespace</kw>
			<kw>while</kw>
			<kw>break</kw>
			<kw>protected</kw>
			<kw>extern</kw>
			<kw>if</kw>
			<kw>static_cast</kw>
			<kw>typeid</kw>
			<kw>inline</kw>
			<kw>delete</kw>
			<kw>do</kw>
			<kw>template</kw>
			<kw>else</kw>
			<kw>dynamic_cast</kw>
			<kw>return</kw>
			<kw>class</kw>
			<kw>enum</kw>
			<kw>reinterpret_cast</kw>
			<kw>new</kw>
			<kw>default</kw>
			<kw>explicit</kw>
			<kw>wchar_t</kw>
			<kw>typename</kw>
			<kw>continue</kw>
			<kw>case</kw>
			<kw>public</kw>
			<kw>this</kw>
			<kw>try</kw>
			<kw>friend</kw>
		</def>
	</keywords>
	<colors>
		<numbers>
			<attr name="fontColor" value="#800080"/>
		</numbers>
		<strings id="2">
			<attr name="fontColor" value="#FF00FF"/>
		</strings>
		<strings id="1">
			<attr name="fontColor" value="#FF00FF"/>
		</strings>
		<slComments id="2">
			<attr name="fontColor" value="#008080"/>
		</slComments>
		<slComments id="1">
			<attr name="fontColor" value="#008000"/>
		</slComments>
		<mlComments id="1">
			<attr name="fontColor" value="#0000FF"/>
		</mlComments>
		<symbols>
			<attr name="fontColor" value="#800000"/>
		</symbols>
		<keywords id="3">
			<attr name="fontColor" value="#FF0000"/>
		</keywords>
		<keywords id="2">
			<attr name="fontColor" value="#2E8B57"/>
			<attr name="bold" value="true"/>
		</keywords>
		<keywords id="1">
			<attr name="fontColor" value="#A52A2A"/>
			<attr name="bold" value="true"/>
		</keywords>
	</colors>
</highlighter>

=== script-solution/Boardsolution/bbceditor/highlighter/bash.xml
<?xml version="1.0" encoding="UTF-8"?>
<highlighter xmlns="http://www.script-solution.de/schemas/bs/bbc/language"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.script-solution.de/schemas/bs/bbc/language language.xsd">
	<name>Bash</name>
	<hlNumbers>true</hlNumbers>
	<escapeChar>\</escapeChar>
	<stringQuotes>
		<def id="2">&quot;</def>
		<def id="1">&#039;</def>
	</stringQuotes>
	<slComments>
		<def id="1">#</def>
	</slComments>
	<mlComments>
	</mlComments>
	<symbols>
		<kw>(</kw>
		<kw>)</kw>
		<kw>[</kw>
		<kw>]</kw>
		<kw>!</kw>
		<kw>@</kw>
		<kw>%</kw>
		<kw>&amp;</kw>
		<kw>*</kw>
		<kw>|</kw>
		<kw>/</kw>
		<kw>&gt;</kw>
		<kw>&lt;</kw>
		<kw>;;</kw>
	</symbols>
	<regexps>
		<def id="1" pattern="\$\{[a-zA-Z_][a-zA-Z0-9_]*?\}" cs="0"/>
		<def id="2" pattern="\$[a-zA-Z_][a-zA-Z0-9_]*" cs="0"/>
		<def id="3" pattern="([a-zA-Z_][a-zA-Z0-9_]*)=" cs="0"/>
		<def id="4" pattern="(?&lt;!\$)#[^\n]*" cs="0"/>
		<def id="5" pattern="\$#" cs="0"/>
	</regexps>
	<keywords>
		<def id="2" cs="false">
			<kw>aclocal</kw>
			<kw>aconnect</kw>
			<kw>aplay</kw>
			<kw>apm</kw>
			<kw>apmsleep</kw>
			<kw>apropos</kw>
			<kw>ar</kw>
			<kw>arch</kw>
			<kw>arecord</kw>
			<kw>as</kw>
			<kw>as86</kw>
			<kw>autoconf</kw>
			<kw>autoheader</kw>
			<kw>automake</kw>
			<kw>awk</kw>
			<kw>basename</kw>
			<kw>bc</kw>
			<kw>bison</kw>
			<kw>bunzip2</kw>
			<kw>bzip2</kw>
			<kw>bzcat</kw>
			<kw>bzcmp</kw>
			<kw>bzdiff</kw>
			<kw>bzegrep</kw>
			<kw>bzegrep</kw>
			<kw>bzfgrep</kw>
			<kw>bzgrep</kw>
			<kw>bzip2</kw>
			<kw>bzip2recover</kw>
			<kw>bzless</kw>
			<kw>bzmore</kw>
			<kw>c++</kw>
			<kw>cal</kw>
			<kw>cat</kw>
			<kw>chattr</kw>
			<kw>cc</kw>
			<kw>cdda2wav</kw>
			<kw>cdparanoia</kw>
			<kw>cdrdao</kw>
			<kw>cd-read</kw>
			<kw>cdrecord</kw>
			<kw>chfn</kw>
			<kw>chgrp</kw>
			<kw>chmod</kw>
			<kw>chown</kw>
			<kw>chroot</kw>
			<kw>chsh</kw>
			<kw>chvt</kw>
			<kw>clear</kw>
			<kw>cmp</kw>
			<kw>comm</kw>
			<kw>co</kw>
			<kw>col</kw>
			<kw>cp</kw>
			<kw>cpio</kw>
			<kw>cpp</kw>
			<kw>cut</kw>
			<kw>date</kw>
			<kw>dd</kw>
			<kw>dc</kw>
			<kw>dcop</kw>
			<kw>deallocvt</kw>
			<kw>df</kw>
			<kw>diff</kw>
			<kw>diff3</kw>
			<kw>dir</kw>
			<kw>dircolors</kw>
			<kw>directomatic</kw>
			<kw>dirname</kw>
			<kw>dmesg</kw>
			<kw>dnsdomainname</kw>
			<kw>domainname</kw>
			<kw>du</kw>
			<kw>dumpkeys</kw>
			<kw>ed</kw>
			<kw>egrep</kw>
			<kw>env</kw>
			<kw>expr</kw>
			<kw>false</kw>
			<kw>fbset</kw>
			<kw>fgconsole</kw>
			<kw>fgrep</kw>
			<kw>find</kw>
			<kw>file</kw>
			<kw>flex</kw>
			<kw>flex++</kw>
			<kw>fmt</kw>
			<kw>free</kw>
			<kw>ftp</kw>
			<kw>funzip</kw>
			<kw>fuser</kw>
			<kw>g++</kw>
			<kw>gawk</kw>
			<kw>gc</kw>
			<kw>gcc</kw>
			<kw>gdb</kw>
			<kw>getent</kw>
			<kw>getkeycodes</kw>
			<kw>getopt</kw>
			<kw>gettext</kw>
			<kw>gettextize</kw>
			<kw>gimp</kw>
			<kw>gimp-remote</kw>
			<kw>gimptool</kw>
			<kw>gmake</kw>
			<kw>gocr</kw>
			<kw>grep</kw>
			<kw>groups</kw>
			<kw>gs</kw>
			<kw>gunzip</kw>
			<kw>gzexe</kw>
			<kw>gzip</kw>
			<kw>head</kw>
			<kw>hexdump</kw>
			<kw>hostname</kw>
			<kw>id</kw>
			<kw>igawk</kw>
			<kw>install</kw>
			<kw>join</kw>
			<kw>kbd_mode</kw>
			<kw>kbdrate</kw>
			<kw>kdialog</kw>
			<kw>kfile</kw>
			<kw>kill</kw>
			<kw>killall</kw>
			<kw>last</kw>
			<kw>lastb</kw>
			<kw>ld</kw>
			<kw>ld86</kw>
			<kw>ldd</kw>
			<kw>less</kw>
			<kw>lex</kw>
			<kw>link</kw>
			<kw>ln</kw>
			<kw>loadkeys</kw>
			<kw>loadunimap</kw>
			<kw>locate</kw>
			<kw>lockfile</kw>
			<kw>login</kw>
			<kw>logname</kw>
			<kw>lp</kw>
			<kw>lpr</kw>
			<kw>ls</kw>
			<kw>lsattr</kw>
			<kw>lsmod</kw>
			<kw>lsmod.old</kw>
			<kw>lynx</kw>
			<kw>m4</kw>
			<kw>make</kw>
			<kw>man</kw>
			<kw>mapscrn</kw>
			<kw>mesg</kw>
			<kw>mkdir</kw>
			<kw>mkfifo</kw>
			<kw>mknod</kw>
			<kw>mktemp</kw>
			<kw>more</kw>
			<kw>mount</kw>
			<kw>msgfmt</kw>
			<kw>mv</kw>
			<kw>namei</kw>
			<kw>nano</kw>
			<kw>nasm</kw>
			<kw>nawk</kw>
			<kw>netstat</kw>
			<kw>nice</kw>
			<kw>nisdomainname</kw>
			<kw>nl</kw>
			<kw>nm</kw>
			<kw>nm86</kw>
			<kw>nmap</kw>
			<kw>nohup</kw>
			<kw>nop</kw>
			<kw>od</kw>
			<kw>openvt</kw>
			<kw>passwd</kw>
			<kw>patch</kw>
			<kw>pcregrep</kw>
			<kw>pcretest</kw>
			<kw>perl</kw>
			<kw>perror</kw>
			<kw>pgawk</kw>
			<kw>pidof</kw>
			<kw>ping</kw>
			<kw>pr</kw>
			<kw>procmail</kw>
			<kw>prune</kw>
			<kw>ps</kw>
			<kw>pstree</kw>
			<kw>ps2ascii</kw>
			<kw>ps2epsi</kw>
			<kw>ps2frag</kw>
			<kw>ps2pdf</kw>
			<kw>ps2ps</kw>
			<kw>psbook</kw>
			<kw>psmerge</kw>
			<kw>psnup</kw>
			<kw>psresize</kw>
			<kw>psselect</kw>
			<kw>pstops</kw>
			<kw>rbash</kw>
			<kw>rcs</kw>
			<kw>read</kw>
			<kw>readlink</kw>
			<kw>red</kw>
			<kw>resizecons</kw>
			<kw>rev</kw>
			<kw>rm</kw>
			<kw>rmdir</kw>
			<kw>run-parts</kw>
			<kw>sash</kw>
			<kw>sed</kw>
			<kw>setfont</kw>
			<kw>setkeycodes</kw>
			<kw>setleds</kw>
			<kw>setmetamode</kw>
			<kw>setserial</kw>
			<kw>scp</kw>
			<kw>seq</kw>
			<kw>setterm</kw>
			<kw>sh</kw>
			<kw>showkey</kw>
			<kw>shred</kw>
			<kw>size</kw>
			<kw>size86</kw>
			<kw>skill</kw>
			<kw>sleep</kw>
			<kw>slogin</kw>
			<kw>snice</kw>
			<kw>sort</kw>
			<kw>sox</kw>
			<kw>split</kw>
			<kw>ssed</kw>
			<kw>ssh</kw>
			<kw>ssh-add</kw>
			<kw>ssh-agent</kw>
			<kw>ssh-keygen</kw>
			<kw>ssh-keyscan</kw>
			<kw>stat</kw>
			<kw>strings</kw>
			<kw>strip</kw>
			<kw>stty</kw>
			<kw>su</kw>
			<kw>sudo</kw>
			<kw>suidperl</kw>
			<kw>sum</kw>
			<kw>sync</kw>
			<kw>tac</kw>
			<kw>tail</kw>
			<kw>tar</kw>
			<kw>tee</kw>
			<kw>tempfile</kw>
			<kw>touch</kw>
			<kw>tr</kw>
			<kw>true</kw>
			<kw>umount</kw>
			<kw>uname</kw>
			<kw>unicode_start</kw>
			<kw>unicode_stop</kw>
			<kw>uniq</kw>
			<kw>unlink</kw>
			<kw>unzip</kw>
			<kw>updatedb</kw>
			<kw>updmap</kw>
			<kw>uptime</kw>
			<kw>users</kw>
			<kw>utmpdump</kw>
			<kw>uuidgen</kw>
			<kw>vdir</kw>
			<kw>vmstat</kw>
			<kw>w</kw>
			<kw>wall</kw>
			<kw>wc</kw>
			<kw>wget</kw>
			<kw>whatis</kw>
			<kw>whereis</kw>
			<kw>which</kw>
			<kw>who</kw>
			<kw>whoami</kw>
			<kw>write</kw>
			<kw>xargs</kw>
			<kw>xhost</kw>
			<kw>xmodmap</kw>
			<kw>xset</kw>
			<kw>yacc</kw>
			<kw>yes</kw>
			<kw>ypdomainname</kw>
			<kw>zcat</kw>
			<kw>zcmp</kw>
			<kw>zdiff</kw>
			<kw>zegrep</kw>
			<kw>zfgrep</kw>
			<kw>zforce</kw>
			<kw>zgrep</kw>
			<kw>zip</kw>
			<kw>zless</kw>
			<kw>zmore</kw>
			<kw>znew</kw>
			<kw>zsh</kw>
			<kw>zsoelim</kw>
		</def>
		<def id="1" cs="false">
			<kw>case</kw>
			<kw>do</kw>
			<kw>done</kw>
			<kw>elif</kw>
			<kw>else</kw>
			<kw>esac</kw>
			<kw>fi</kw>
			<kw>for</kw>
			<kw>function</kw>
			<kw>if</kw>
			<kw>in</kw>
			<kw>select</kw>
			<kw>set</kw>
			<kw>then</kw>
			<kw>until</kw>
			<kw>while</kw>
			<kw>time</kw>
		</def>
		<def id="3" cs="false">
			<kw>alias</kw>
			<kw>bg</kw>
			<kw>bind</kw>
			<kw>break</kw>
			<kw>builtin</kw>
			<kw>cd</kw>
			<kw>command</kw>
			<kw>compgen</kw>
			<kw>complete</kw>
			<kw>continue</kw>
			<kw>declare</kw>
			<kw>dirs</kw>
			<kw>disown</kw>
			<kw>echo</kw>
			<kw>enable</kw>
			<kw>eval</kw>
			<kw>exec</kw>
			<kw>exit</kw>
			<kw>export</kw>
			<kw>fc</kw>
			<kw>fg</kw>
			<kw>getopts</kw>
			<kw>hash</kw>
			<kw>help</kw>
			<kw>history</kw>
			<kw>jobs</kw>
			<kw>kill</kw>
			<kw>let</kw>
			<kw>local</kw>
			<kw>logout</kw>
			<kw>popd</kw>
			<kw>printf</kw>
			<kw>pushd</kw>
			<kw>pwd</kw>
			<kw>readonly</kw>
			<kw>return</kw>
			<kw>shift</kw>
			<kw>shopt</kw>
			<kw>source</kw>
			<kw>suspend</kw>
			<kw>test</kw>
			<kw>times</kw>
			<kw>trap</kw>
			<kw>type</kw>
			<kw>typeset</kw>
			<kw>ulimit</kw>
			<kw>umask</kw>
			<kw>unalias</kw>
			<kw>unset</kw>
			<kw>wait</kw>
		</def>
	</keywords>
	<colors>
		<numbers>
			<attr name="fontColor" value="#800080"/>
		</numbers>
		<strings id="2">
			<attr name="fontColor" value="#FF00FF"/>
		</strings>
		<strings id="1">
			<attr name="fontColor" value="#FF00FF"/>
		</strings>
		<slComments id="1">
			<attr name="fontColor" value="#0000ff"/>
			<attr name="italic" value="true"/>
		</slComments>
		<symbols>
			<attr name="fontColor" value="#000000"/>
			<attr name="bold" value="true"/>
		</symbols>
		<regexp id="1">
			<attr name="fontColor" value="#007800"/>
		</regexp>
		<regexp id="2">
			<attr name="fontColor" value="#007800"/>
		</regexp>
		<regexp id="3">
			<attr name="fontColor" value="#008A8C"/>
		</regexp>
		<regexp id="4">
			<attr name="fontColor" value="#0000ff"/>
			<attr name="italic" value="true"/>
		</regexp>
		<regexp id="5">
			<attr name="fontColor" value="#007800"/>
		</regexp>
		<keywords id="1">
			<attr name="fontColor" value="#A52A2A"/>
			<attr name="bold" value="true"/>
		</keywords>
		<keywords id="2">
			<attr name="fontColor" value="#A52A2A"/>
			<attr name="bold" value="true"/>
		</keywords>
		<keywords id="3">
			<attr name="fontColor" value="#A52A2A"/>
			<attr name="bold" value="true"/>
		</keywords>
	</colors>
</highlighter>
